name: Artifact Attestation Example

on:
  workflow_call:

jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    outputs:
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifact file
        run: echo "Hello, Arkanoid!" > artifact.txt

      - name: Generate artifact attestation (build provenance)
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'artifact.txt'
          subject-name: 'krical'
          show-summary: false

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: artifact.txt

      - name: Print attestation fields
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
        run: |
          echo "GITHUB.WORKFLOW: $WORKFLOW_NAME"
          echo "GITHUB.WORKFLOW_REF: $WORKFLOW_REF"
          echo '${{ toJson(github) }}'

  validate:
    needs: build-and-attest
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-artifact
      - name: Validate artifact attestation
        run: |
          echo "[INFO] Inizio validazione attestation..."
          gh attestation verify ${{ env.ARTIFACT_PATH }} --owner christian-calabrese --signer-workflow christian-calabrese/ArkaPoyd/.github/workflows/artifact-attestation.yml
          STATUS=$?
          if [ $STATUS -eq 0 ]; then
            echo "[SUCCESS] Attestazione valida!"
          else
            echo "[ERROR] Attestazione NON valida!"
            exit $STATUS
          fi
        env:
          ARTIFACT_PATH: "./artifact.txt"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUBJECT_NAME: 'dx'
          EXPECTED_JOB: ${{ github.job }}