name: Artifact Attestation Example

on:
  workflow_call:
env:
  BUNDLE_NAME: example-artifact
jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    outputs:
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - name: Check if artifact already exists in this run
        id: check-artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          echo "::debug::Checking for existing artifact named '${BUNDLE_NAME}' in current run ${GITHUB_RUN_ID}"
          names=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts \
            -q '.artifacts[].name' || true)
          if echo "${names}" | grep -qx "${BUNDLE_NAME}"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "### Artifact already exists ✅" >> "$GITHUB_STEP_SUMMARY"
            echo "Skipping build and upload in this invocation." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Checkout repository
        if: ${{ steps.check-artifact.outputs.exists != 'true' }}
        uses: actions/checkout@v4

      - name: Create artifact file
        if: ${{ steps.check-artifact.outputs.exists != 'true' }}
        run: echo "Hello, Arkanoid!" > artifact.txt

      - name: Upload artifact
        if: ${{ steps.check-artifact.outputs.exists != 'true' }}
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: artifact.txt

      - name: Generate artifact attestation (build provenance)
        if: ${{ steps.check-artifact.outputs.exists != 'true' }}
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'artifact.txt'
          show-summary: false

  validate:
    needs: build-and-attest
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Validate artifact attestation
        run: |
          gh attestation verify ${{ env.ARTIFACT_PATH }} --owner christian-calabrese --signer-workflow christian-calabrese/ArkaPoyd/.github/workflows/artifact-attestation.yml
        env:
          ARTIFACT_PATH: "./artifact.txt"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
