name: Artifact Attestation Example

on:
  workflow_call:
jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifact file
        run: echo "Hello, Arkanoid!" > artifact.txt

      - name: Generate artifact attestation (build provenance)
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'artifact.txt'
          subject-name: 'krical'
          show-summary: false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: artifact.txt

      - name: Print attestation fields
        env: 
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
        run: |
          echo "GITHUB.WORKFLOW: $WORKFLOW_NAME"
          echo "GITHUB.WORKFLOW_REF: $WORKFLOW_REF"
          echo '${{ toJson(github) }}'


